### ISSUE TITLE
Every function except download doesn't work

### ISSUE THREAD

**Issue by 12ohit** [AgentHackerYT/vadapav.mov#1]
Basically everything that uses https://vadapav.mov/api doesn't work so that leaves only download function which is working right now

**Comment by AgentHackerYT** [comment]
I have made a scrapper which does not use /api endpoint and it works but the vadapav owner is not allowing me as of now to publish it as the api is one of the major reason for ddos attacks. as of now there is nothing I could do. 
Sorry!
